name: Set up Python environment

runs:
  using: composite
  steps:
    - name: Get Python version
      id: python-version
      run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: ${{ steps.python-version.outputs.version }}
        cache: pip

    - run: pip install -r requirements-dev.txt
      shell: bash
