---
name: Continuous Integration

on:
  push:
    branches:
      - main
    paths:
      - 'src/bitcoin_indexer/*.py'
      - 'tests/*.py'
  pull_request:
    paths:
      - 'src/bitcoin_indexer/*.py'
      - 'tests/*.py'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7

      - name: Get Python version
        id: python-version
        run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ steps.python-version.outputs.version }}

      - name: Install pylint
        run: |
          pip install -r requirements-dev.txt

      - name: Run pylint
        run: pylint src/bitcoin_indexer
